

export const posts = [
  {
    id: 1,
    title: "Introducing Aliens On The Ave",
    subtitle: "ALIENS ON THE AVE NFT",
    src: "/images/blog/slide1.png",
    author: "Jake Flores",
    date: "August 17, 2022",
    category: "ALIENS ON THE AVE NFT",
    href: '/blog-details',
    DetailsBody: "BlogDetailsBody1",    
  },
  {
    id: 2,
    title: "Working From Home During Quarantine",
    subtitle: "ORGANIZING, PERSONAL GROWTH",
    src: "/images/blog/slide5.jpeg",
    author: "Jake Flores",
    date: "April 28, 2020",
    category: "ORGANIZING, PERSONAL GROWTH",
    href: '/blog-details',
    DetailsBody: "BlogDetailsBody2",     
  },
  {
    id: 3,
    title: "Evernote for Business",
    subtitle: "BUSINESS ADVICE, ORGANIZING",
    src: "/images/blog/slide6.png",
    author: "Jake Flores",
    date: "May 7, 2019",
    category: "BUSINESS ADVICE, ORGANIZING",
    href: '/blog-details',
    DetailsBody: "BlogDetailsBody3",
  },
  {
    id: 4,
    title: "Crushing Cans (and Habits)",
    subtitle: "PSYCHOLOGY, PERSONAL GROWTH",
    src: "/images/blog/slide3.jpg",
    author: "Jake Flores",
    date: "May 19, 2019",
    category: "PSYCHOLOGY, PERSONAL GROWTH",
    href: '/blog-details',
    DetailsBody: "BlogDetailsBody4",
  },
  {
    id: 5,
    title: "Find the Right People For Your Business",
    subtitle: "BUSINESS ADVICE, RECRUITING",
    src: "/images/blog/post.jpeg",
    author: "Sam Tavarez",
    date: "April 3, 2017",
    category: "BUSINESS ADVICE, RECRUITING",
    href: '/blog-details',
    DetailsBody: "BlogDetailsBody5",
  },
  {
    id: 6,
    title: "5 Reasons Why Your Business Is Failing",
    subtitle: "",
    src: "/images/blog/slide2.jpeg",
    author: "Jake Flores",
    date: " April 3, 2017",
    category: "",
    href: '/blog-details',    
    DetailsBody: "BlogDetailsBody6",
  },
  {
    id: 7,
    title: "Be Bold and Stand Out!",
    subtitle: "",
    src: "/images/blog/slide4.jpg",
    author: "Jake Flores",
    date: " April 3, 2017",
    category: "",
    href: '/blog-details',
    DetailsBody: "BlogDetailsBody7",
  },
  {
    id: 8,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
    href: '/blog-details'
  },
  {
    id: 9,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
    href: '/blog-details'
  },
  {
    id: 10,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
    href: '/blog-details'
  },
  {
    id: 11,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
    href: '/blog-details'
  },
  {
    id: 12,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
    href: '/blog-details'
  },
  {
    id: 13,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
    href: '/blog-details'
  },
  {
    id: 14,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
    href: '/blog-details'
  },
  {
    id: 15,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
    href: '/blog-details'
  },
  {
    id: 16,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
    href: '/blog-details'
  },
  {
    id: 17,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
    href: '/blog-details'
  },
  {
    id: 18,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
    href: '/blog-details'
  },
  {
    id: 19,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
    href: '/blog-details'
  },
  {
    id: 20,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
    href: '/blog-details'
  },
  {
    id: 21,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
    href: '/blog-details'
  },
  {
    id: 22,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
    href: '/blog-details'
  },
  {
    id: 23,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
    href: '/blog-details'
  },
];
