export const posts = [
  {
    id: 1,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
  },
  {
    id: 2,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
  },
  {
    id: 3,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
  },
  {
    id: 4,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
  },
  {
    id: 5,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
  },
  {
    id: 6,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
  },
  {
    id: 7,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
  },
  {
    id: 8,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
  },
  {
    id: 9,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
  },
  {
    id: 10,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
  },
  {
    id: 11,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
  },
  {
    id: 12,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
  },
  {
    id: 13,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
  },
  {
    id: 14,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
  },
  {
    id: 15,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
  },
  {
    id: 16,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
  },
  {
    id: 17,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
  },
  {
    id: 18,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
  },
  {
    id: 19,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
  },
  {
    id: 20,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
  },
  {
    id: 21,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
  },
  {
    id: 22,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
  },
  {
    id: 23,
    title: "Like meadowlark while onto this this that dully some far wound",
    src: "/images/blog/post.jpeg",
    author: "DIANNE RUSSEL",
    date: "OCTOBER 25,2022",
    category: "SPORTS",
  },
];
